apiVersion: v1
kind: ConfigMap
metadata:
  name: ztiam-policy-config
  namespace: ztiam
data:
  NODE_ENV: "production"
  PORT: "4000"
  ML_SERVICE_ENABLED: "true"
  ML_SERVICE_URL: "http://ml-service:5000"
  FABRIC_CHANNEL: "iamchannel"
  FABRIC_CHAINCODE: "iam-cc"
  FABRIC_MSP_ID: "Org1MSP"
  FABRIC_PEER_ENDPOINT: "peer0.org1.example.com:7051"
